### PR TITLE
Add missing stdio.h include in send_nsca.c

### PR DESCRIPTION
**Pull request by xavierba**
Add missing stdio.h include in send_nsca.c

Fixes a build warning:
./send_nsca.c: In function 'alarm_handler':
./send_nsca.c:547:2: warning: implicit declaration of function 'asprintf'; did you mean 'vsprintf'? [-Wimplicit-function-declaration]
  547 |  asprintf(&msg, "Error: Timeout after %d seconds\n",socket_timeout);
      |  ^~~~~~~~
      |  vsprintf

This was introduced in 413b313af603a90bc71b72c0f286a01661a1b365

### CODE REVIEW

**Comment by xavierba** [comment]
It would have been nice to have that in 2.10.1.

**Comment by jomann09** [comment]
Merging this for a 2.10.2
